/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Classification Metrics */
        get: operations["getClassificationMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source Health */
        get: operations["getSourceHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Source Item */
        post: operations["createStoryFromSourceItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stories */
        get: operations["listStories"];
        put?: never;
        /** Ingest Story */
        post: operations["createStory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story */
        get: operations["getStory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stories/{story_id}/audio/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audio Clip */
        get: operations["getAudioClip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stories/{story_id}/production-manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Production Manifest */
        get: operations["getProductionManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stories/{story_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Story */
        post: operations["resumeStory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stories/{story_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review History */
        get: operations["listStoryReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stories/{story_id}/reviews/first": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** First Review */
        post: operations["submitFirstReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stories/{story_id}/reviews/second": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Second Review */
        post: operations["submitSecondReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stories/{story_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transition History */
        get: operations["listStoryTransitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Attribution */
        Attribution: {
            /** Attribution Text */
            attribution_text: string;
            /** Author */
            author?: string | null;
            /**
             * Original Url
             * Format: uri
             */
            original_url: string;
            /** Publisher */
            publisher: string;
            /**
             * Source
             * @enum {string}
             */
            source: "dazhong" | "reddit" | "guardian" | "pikabu";
        };
        /** AudioBundle */
        AudioBundle: {
            /** Clips */
            clips: components["schemas"]["AudioClip"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Model Identity */
            model_identity: string;
            /** Provider */
            provider: string;
            /** Revision */
            revision: number;
            synthesis: components["schemas"]["SynthesisMetadata"];
        };
        /** AudioClip */
        AudioClip: {
            /** Channels */
            channels: number;
            /** Duration Ms */
            duration_ms: number;
            /** @default wav */
            format: components["schemas"]["AudioFormat"];
            /** Path */
            path: string;
            /** Sample Rate Hz */
            sample_rate_hz: number;
            /**
             * Segment Id
             * Format: uuid
             */
            segment_id: string;
            /** Sha256 */
            sha256: string;
        };
        /**
         * AudioFormat
         * @enum {string}
         */
        AudioFormat: "wav";
        /** AudioMediaAsset */
        AudioMediaAsset: {
            /** Caption */
            caption?: string | null;
            /** Credit */
            credit?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "audio";
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** ClassificationMetrics */
        ClassificationMetrics: {
            /** Accepted Count */
            accepted_count: number;
            /** Accuracy */
            accuracy?: number | null;
            /** Reviewed Count */
            reviewed_count: number;
        };
        /**
         * ContentCategory
         * @enum {string}
         */
        ContentCategory: "kindness" | "cats_dogs" | "forum" | "short_video";
        /** ContentFlags */
        ContentFlags: {
            /**
             * Has Audio
             * @default false
             */
            has_audio: boolean;
            /**
             * Has Images
             * @default false
             */
            has_images: boolean;
            /**
             * Has Video
             * @default false
             */
            has_video: boolean;
            /**
             * Is Nsfw
             * @default false
             */
            is_nsfw: boolean;
            /**
             * Is Spoiler
             * @default false
             */
            is_spoiler: boolean;
            /** Is User Generated */
            is_user_generated: boolean;
            /**
             * Requires Rights Review
             * @default true
             */
            requires_rights_review: boolean;
        };
        /** DazhongSourceFields */
        DazhongSourceFields: {
            /** Article Id */
            article_id: string;
            /** Channel */
            channel?: string | null;
            /** Region */
            region?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "dazhong";
            /** Tags */
            tags?: string[];
        };
        /**
         * EditorialScreening
         * @description AI screening evidence plus the current human-reviewable decision.
         *
         *     Model fields are immutable evidence. Review edits update only ``category``
         *     and ``candidate_recommendation``, so acceptance metrics remain auditable.
         */
        EditorialScreening: {
            /** Candidate Recommendation */
            candidate_recommendation: boolean;
            category: components["schemas"]["ContentCategory"];
            /** Confidence */
            confidence: number;
            /** Model Candidate Recommendation */
            model_candidate_recommendation: boolean;
            model_category: components["schemas"]["ContentCategory"];
            /** Rationale */
            rationale: string;
            /** Risk Flags */
            risk_flags?: string[];
            /** Secondary Categories */
            secondary_categories?: components["schemas"]["ContentCategory"][];
        };
        /** FirstReviewSubmission */
        FirstReviewSubmission: {
            /** Corrected Candidate Recommendation */
            corrected_candidate_recommendation?: boolean | null;
            corrected_category?: components["schemas"]["ContentCategory"] | null;
            /** Corrected Key Points */
            corrected_key_points?: string[] | null;
            /** Corrected Summary */
            corrected_summary?: string | null;
            /** Corrected Translation */
            corrected_translation?: string | null;
            decision: components["schemas"]["ReviewDecision"];
            /** Expected Story Version */
            expected_story_version: number;
            /** Note */
            note?: string | null;
            preferences?: components["schemas"]["ScriptPreferences"] | null;
            /**
             * Review Id
             * Format: uuid
             */
            review_id?: string;
            /** Reviewer Id */
            reviewer_id: string;
        };
        /** GuardianSourceFields */
        GuardianSourceFields: {
            /** Article Id */
            article_id: string;
            /** Pillar Name */
            pillar_name?: string | null;
            /** Section Id */
            section_id?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "guardian";
            /** Tags */
            tags?: string[];
            /** Trail Text */
            trail_text?: string | null;
        };
        /** HealthReport */
        HealthReport: {
            /** Checks */
            checks: string[];
            /** Ready */
            ready: boolean;
        };
        /** ImageMediaAsset */
        ImageMediaAsset: {
            /** Alt Text */
            alt_text?: string | null;
            /** Credit */
            credit?: string | null;
            /** Height */
            height?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "image";
            /**
             * Role
             * @default body
             * @enum {string}
             */
            role: "main" | "body" | "thumbnail";
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Width */
            width?: number | null;
        };
        /** IngestRequest */
        IngestRequest: {
            /**
             * Emotion
             * @default neutral
             */
            emotion: string;
            /**
             * Pitch
             * @default 0
             */
            pitch: number;
            /** Source */
            source: components["schemas"]["UrlSource"] | components["schemas"]["TextSource"];
            /**
             * Speaker Id
             * @default narrator
             */
            speaker_id: string;
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /**
             * Style
             * @default clear, accurate short-video narration
             */
            style: string;
            /**
             * Target Duration Seconds
             * @default 90
             */
            target_duration_seconds: number;
            /**
             * Target Language
             * @default zh-CN
             */
            target_language: string;
        };
        /** Liveness */
        Liveness: {
            /**
             * Alive
             * @default true
             */
            alive: boolean;
        };
        /** NormalizedSourceItem */
        NormalizedSourceItem: {
            attribution: components["schemas"]["Attribution"];
            /** Author */
            author?: string | null;
            /**
             * Canonical Url
             * Format: uri
             */
            canonical_url: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Content Text */
            content_text: string;
            /** External Id */
            external_id: string;
            flags: components["schemas"]["ContentFlags"];
            /** Language */
            language: string;
            /** Media */
            media?: (components["schemas"]["ImageMediaAsset"] | components["schemas"]["VideoMediaAsset"] | components["schemas"]["AudioMediaAsset"])[];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            rights: components["schemas"]["RightsMetadata"];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Source
             * @enum {string}
             */
            source: "dazhong" | "reddit" | "guardian" | "pikabu";
            /** Source Fields */
            source_fields: components["schemas"]["DazhongSourceFields"] | components["schemas"]["RedditSourceFields"] | components["schemas"]["GuardianSourceFields"] | components["schemas"]["PikabuSourceFields"];
            /** Title */
            title: string;
        };
        /** PikabuImageBlock */
        PikabuImageBlock: {
            /** Alt Text */
            alt_text?: string | null;
            /** Height */
            height?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "image";
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Width */
            width?: number | null;
        };
        /** PikabuQuoteBlock */
        PikabuQuoteBlock: {
            /** Author */
            author?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "quote";
            /** Text */
            text: string;
        };
        /** PikabuSourceFields */
        PikabuSourceFields: {
            /** Block Count */
            block_count: number;
            /** Comments Count */
            comments_count: number;
            /** Rating */
            rating: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "pikabu";
            /** Story Id */
            story_id: string;
            /** Tags */
            tags?: string[];
        };
        /** PikabuTextBlock */
        PikabuTextBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Text */
            text: string;
        };
        /** PikabuVideoBlock */
        PikabuVideoBlock: {
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "video";
            /** Poster Url */
            poster_url?: string | null;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** PipelineFailure */
        PipelineFailure: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ProblemDetail */
        ProblemDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Story Id */
            story_id?: string | null;
            /** Trace Id */
            trace_id: string;
        };
        /** ProductionManifest */
        ProductionManifest: {
            /** Language */
            language: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Script Revision */
            script_revision: number;
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Timeline */
            timeline: components["schemas"]["TimelineSegment"][];
            /** Total Duration Ms */
            total_duration_ms: number;
        };
        /** RawDazhongImage */
        RawDazhongImage: {
            /** Alt Text */
            alt_text?: string | null;
            /** Credit */
            credit?: string | null;
            /** Height */
            height?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "image";
            /**
             * Role
             * @default body
             * @enum {string}
             */
            role: "main" | "body" | "thumbnail";
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Width */
            width?: number | null;
        };
        /** RawDazhongItem */
        RawDazhongItem: {
            /** Article Id */
            article_id: string;
            /** Author */
            author?: string | null;
            /** Body */
            body: string;
            /** Canonical Url */
            canonical_url?: string | null;
            /** Channel */
            channel?: string | null;
            /**
             * Language
             * @default zh-CN
             */
            language: string;
            /** Media */
            media?: (components["schemas"]["RawDazhongImage"] | components["schemas"]["RawDazhongVideo"])[];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /**
             * Publisher
             * @default 大众新闻
             */
            publisher: string;
            /** Region */
            region?: string | null;
            rights?: components["schemas"]["RawRightsDeclaration"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "dazhong";
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** RawDazhongVideo */
        RawDazhongVideo: {
            /** Caption */
            caption?: string | null;
            /** Credit */
            credit?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "video";
            /** Poster Url */
            poster_url?: string | null;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** RawGuardianAudio */
        RawGuardianAudio: {
            /** Caption */
            caption?: string | null;
            /** Credit */
            credit?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "audio";
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** RawGuardianImage */
        RawGuardianImage: {
            /** Caption */
            caption?: string | null;
            /** Credit */
            credit?: string | null;
            /** Height */
            height?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "image";
            /**
             * Role
             * @default body
             * @enum {string}
             */
            role: "main" | "body" | "thumbnail";
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Width */
            width?: number | null;
        };
        /** RawGuardianItem */
        RawGuardianItem: {
            /** Article Id */
            article_id: string;
            /** Body Text */
            body_text: string;
            /** Byline */
            byline?: string | null;
            /**
             * Language
             * @default en
             */
            language: string;
            /** Media */
            media?: (components["schemas"]["RawGuardianImage"] | components["schemas"]["RawGuardianVideo"] | components["schemas"]["RawGuardianAudio"])[];
            /** Pillar Name */
            pillar_name?: string | null;
            /**
             * Publisher
             * @default The Guardian
             */
            publisher: string;
            rights?: components["schemas"]["RawRightsDeclaration"];
            /** Section Id */
            section_id?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "guardian";
            /** Tags */
            tags?: string[];
            /** Trail Text */
            trail_text?: string | null;
            /**
             * Web Publication Date
             * Format: date-time
             */
            web_publication_date: string;
            /** Web Title */
            web_title: string;
            /**
             * Web Url
             * Format: uri
             */
            web_url: string;
        };
        /** RawGuardianVideo */
        RawGuardianVideo: {
            /** Caption */
            caption?: string | null;
            /** Credit */
            credit?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "video";
            /** Poster Url */
            poster_url?: string | null;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** RawPikabuItem */
        RawPikabuItem: {
            /** Author Username */
            author_username?: string | null;
            /** Blocks */
            blocks: (components["schemas"]["PikabuTextBlock"] | components["schemas"]["PikabuQuoteBlock"] | components["schemas"]["PikabuImageBlock"] | components["schemas"]["PikabuVideoBlock"])[];
            /**
             * Comments Count
             * @default 0
             */
            comments_count: number;
            /**
             * Is Nsfw
             * @default false
             */
            is_nsfw: boolean;
            /**
             * Language
             * @default ru
             */
            language: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /**
             * Publisher
             * @default Pikabu
             */
            publisher: string;
            /**
             * Rating
             * @default 0
             */
            rating: number;
            rights?: components["schemas"]["RawRightsDeclaration"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "pikabu";
            /** Story Id */
            story_id: string;
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /**
         * RawRedditItem
         * @description Sanitized Reddit adapter contract.
         *
         *     Reddit adds fields without notice. Unknown keys are intentionally ignored at
         *     this boundary; every field used downstream remains explicitly declared.
         */
        RawRedditItem: {
            /** Author */
            author?: string | null;
            /**
             * Created Utc
             * Format: date-time
             */
            created_utc: string;
            /**
             * Is Self
             * @default true
             */
            is_self: boolean;
            /**
             * Language
             * @default en
             */
            language: string;
            /** Link Flair Text */
            link_flair_text?: string | null;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /**
             * Num Comments
             * @default 0
             */
            num_comments: number;
            /** Outbound Url */
            outbound_url?: string | null;
            /**
             * Over 18
             * @default false
             */
            over_18: boolean;
            /** Permalink */
            permalink: string;
            /** Post Id */
            post_id: string;
            /** Preview Images */
            preview_images?: components["schemas"]["RawRedditPreviewImage"][];
            rights?: components["schemas"]["RawRightsDeclaration"];
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Selftext
             * @default
             */
            selftext: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "reddit";
            /**
             * Spoiler
             * @default false
             */
            spoiler: boolean;
            /** Subreddit */
            subreddit: string;
            /** Title */
            title: string;
            video?: components["schemas"]["RawRedditVideo"] | null;
        };
        /** RawRedditPreviewImage */
        RawRedditPreviewImage: {
            /** Height */
            height?: number | null;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Width */
            width?: number | null;
        };
        /** RawRedditVideo */
        RawRedditVideo: {
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * Fallback Url
             * Format: uri
             */
            fallback_url: string;
            /**
             * Kind
             * @default video
             * @constant
             */
            kind: "video";
            /** Thumbnail Url */
            thumbnail_url?: string | null;
        };
        /** RawRightsDeclaration */
        RawRightsDeclaration: {
            /** Allows Derivatives */
            allows_derivatives?: boolean | null;
            /** Allows Republication */
            allows_republication?: boolean | null;
            /** Copyright Holder */
            copyright_holder?: string | null;
            /** License Name */
            license_name?: string | null;
            /** License Url */
            license_url?: string | null;
            /**
             * Requires Attribution
             * @default true
             */
            requires_attribution: boolean;
            /**
             * Status
             * @default unknown
             * @enum {string}
             */
            status: "unknown" | "permission_required" | "attribution_license" | "public_domain";
            /** Terms Url */
            terms_url?: string | null;
        };
        /** RedditSourceFields */
        RedditSourceFields: {
            /** Flair */
            flair?: string | null;
            /** Is Self */
            is_self: boolean;
            /** Locked */
            locked: boolean;
            /** Num Comments */
            num_comments: number;
            /** Outbound Url */
            outbound_url?: string | null;
            /** Post Id */
            post_id: string;
            /** Score */
            score: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            source: "reddit";
            /** Subreddit */
            subreddit: string;
        };
        /**
         * ReviewDecision
         * @enum {string}
         */
        ReviewDecision: "approve" | "request_changes";
        /** ReviewRecord */
        ReviewRecord: {
            ai_category?: components["schemas"]["ContentCategory"] | null;
            /** Audio Sha256 */
            audio_sha256?: string | null;
            /** Classification Accepted */
            classification_accepted?: boolean | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            decision: components["schemas"]["ReviewDecision"];
            human_category?: components["schemas"]["ContentCategory"] | null;
            /** Note */
            note?: string | null;
            /** Request Sha256 */
            request_sha256: string;
            /**
             * Review Id
             * Format: uuid
             */
            review_id?: string;
            /** Reviewed Story Version */
            reviewed_story_version: number;
            /** Reviewer Id */
            reviewer_id: string;
            /** Script Revision */
            script_revision?: number | null;
            stage: components["schemas"]["ReviewStage"];
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Translation Sha256 */
            translation_sha256: string;
        };
        /**
         * ReviewStage
         * @enum {string}
         */
        ReviewStage: "first" | "second";
        /** RightsMetadata */
        RightsMetadata: {
            /** Allows Derivatives */
            allows_derivatives?: boolean | null;
            /** Allows Republication */
            allows_republication?: boolean | null;
            /** Copyright Holder */
            copyright_holder?: string | null;
            /** License Name */
            license_name?: string | null;
            /** License Url */
            license_url?: string | null;
            /** Requires Attribution */
            requires_attribution: boolean;
            /** Requires Human Review */
            requires_human_review: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "unknown" | "permission_required" | "attribution_license" | "public_domain";
            /** Terms Url */
            terms_url?: string | null;
        };
        /** ScriptDocument */
        ScriptDocument: {
            /** Language */
            language: string;
            /**
             * Revision
             * @default 1
             */
            revision: number;
            /** Segments */
            segments: components["schemas"]["ScriptSegment"][];
            /** Title */
            title: string;
        };
        /** ScriptPreferences */
        ScriptPreferences: {
            /**
             * Emotion
             * @default neutral
             */
            emotion: string;
            /**
             * Pitch
             * @default 0
             */
            pitch: number;
            /** Speaker Id */
            speaker_id: string;
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /** Style */
            style: string;
            /** Target Duration Seconds */
            target_duration_seconds: number;
        };
        /** ScriptSegment */
        ScriptSegment: {
            /** Emotion */
            emotion: string;
            /** Pitch */
            pitch: number;
            /**
             * Segment Id
             * Format: uuid
             */
            segment_id?: string;
            /** Sequence */
            sequence: number;
            /** Speaker Id */
            speaker_id: string;
            /** Speed */
            speed: number;
            /** Text */
            text: string;
            /** Visual Hint */
            visual_hint?: string | null;
        };
        /** SecondReviewSubmission */
        SecondReviewSubmission: {
            decision: components["schemas"]["ReviewDecision"];
            /** Expected Story Version */
            expected_story_version: number;
            /** Note */
            note?: string | null;
            /**
             * Review Id
             * Format: uuid
             */
            review_id?: string;
            /** Reviewer Id */
            reviewer_id: string;
            revised_script?: components["schemas"]["ScriptDocument"] | null;
        };
        /** SourceHealth */
        SourceHealth: {
            /**
             * Access Method
             * @enum {string}
             */
            access_method: "official_api" | "authorized_public_page" | "typed_contract_only";
            /** Authorized */
            authorized: boolean;
            /** Configured */
            configured: boolean;
            /** Contract Ok */
            contract_ok: boolean;
            /** Notes */
            notes?: string[];
            /** Reachable */
            reachable: boolean | null;
            /**
             * Source
             * @enum {string}
             */
            source: "dazhong" | "reddit" | "guardian" | "pikabu";
        };
        /** SourceHealthReport */
        SourceHealthReport: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at?: string;
            /** Network Probed */
            network_probed: boolean;
            /** Sources */
            sources: components["schemas"]["SourceHealth"][];
        };
        /**
         * SourceItemIngestRequest
         * @description Trusted adapter boundary for one of the four fixed sources.
         *
         *     Network-facing adapters must map their documented/authorized response into
         *     ``RawSourceItem`` before calling this boundary. The core never consumes an
         *     upstream provider's unvalidated mapping.
         */
        SourceItemIngestRequest: {
            /**
             * Emotion
             * @default neutral
             */
            emotion: string;
            /** Item */
            item: components["schemas"]["RawDazhongItem"] | components["schemas"]["RawRedditItem"] | components["schemas"]["RawGuardianItem"] | components["schemas"]["RawPikabuItem"];
            /**
             * Pitch
             * @default 0
             */
            pitch: number;
            /**
             * Speaker Id
             * @default narrator
             */
            speaker_id: string;
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /**
             * Style
             * @default clear, accurate short-video narration
             */
            style: string;
            /**
             * Target Duration Seconds
             * @default 90
             */
            target_duration_seconds: number;
            /**
             * Target Language
             * @default zh-CN
             */
            target_language: string;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "url" | "text" | "fixed_source";
        /** SourceSnapshot */
        SourceSnapshot: {
            /** Author */
            author?: string | null;
            /** Content Sha256 */
            content_sha256: string;
            /** Detected Language */
            detected_language?: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at?: string;
            /** Fetcher */
            fetcher: string;
            /** Final Uri */
            final_uri: string;
            kind: components["schemas"]["SourceKind"];
            /** Published At */
            published_at?: string | null;
            /** Source Uri */
            source_uri: string;
            /** Title */
            title: string;
        };
        /** StateTransition */
        StateTransition: {
            from_status: components["schemas"]["StoryStatus"];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
            /** Reason */
            reason: string;
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            to_status: components["schemas"]["StoryStatus"];
            /**
             * Transition Id
             * Format: uuid
             */
            transition_id?: string;
        };
        /** Story */
        Story: {
            audio?: components["schemas"]["AudioBundle"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            last_failure?: components["schemas"]["PipelineFailure"] | null;
            /** Original Text */
            original_text: string;
            preferences: components["schemas"]["ScriptPreferences"];
            provenance?: components["schemas"]["NormalizedSourceItem"] | null;
            script?: components["schemas"]["ScriptDocument"] | null;
            source: components["schemas"]["SourceSnapshot"];
            status: components["schemas"]["StoryStatus"];
            /**
             * Story Id
             * Format: uuid
             */
            story_id?: string;
            /** Target Language */
            target_language: string;
            /**
             * Trace Id
             * Format: uuid
             */
            trace_id?: string;
            translation?: components["schemas"]["TranslationResult"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /**
         * StoryStatus
         * @enum {string}
         */
        StoryStatus: "FETCHED" | "TRANSLATED" | "PENDING_FIRST_REVIEW" | "PROCESSING_SCRIPT" | "SCRIPT_READY" | "PENDING_SECOND_REVIEW" | "DONE";
        /** SynthesisMetadata */
        SynthesisMetadata: {
            /** Gpt Weights Sha256 */
            gpt_weights_sha256: string;
            /** Prompt Language */
            prompt_language: string;
            /** Reference Audio Sha256 */
            reference_audio_sha256: string;
            /** Runtime Config Sha256 */
            runtime_config_sha256: string;
            /** Seed */
            seed: number;
            /** Sovits Weights Sha256 */
            sovits_weights_sha256: string;
            /** Text Language */
            text_language: string;
        };
        /** TextSource */
        TextSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Language */
            language?: string | null;
            /** Text */
            text: string;
            /**
             * Title
             * @default Uploaded text
             */
            title: string;
        };
        /** TimelineSegment */
        TimelineSegment: {
            /** Audio Path */
            audio_path: string;
            /** Emotion */
            emotion: string;
            /** End Ms */
            end_ms: number;
            /**
             * Segment Id
             * Format: uuid
             */
            segment_id: string;
            /** Sequence */
            sequence: number;
            /** Speaker Id */
            speaker_id: string;
            /** Start Ms */
            start_ms: number;
            /** Text */
            text: string;
            /** Visual Hint */
            visual_hint?: string | null;
        };
        /** TranslationResult */
        TranslationResult: {
            /** Key Points */
            key_points?: string[];
            screening: components["schemas"]["EditorialScreening"];
            /** Source Language */
            source_language: string;
            /** Summary */
            summary: string;
            /** Target Language */
            target_language: string;
            /** Translated Text */
            translated_text: string;
        };
        /** UrlSource */
        UrlSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "url";
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** VideoMediaAsset */
        VideoMediaAsset: {
            /** Caption */
            caption?: string | null;
            /** Credit */
            credit?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "video";
            /** Poster Url */
            poster_url?: string | null;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
    getClassificationMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassificationMetrics"];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getSourceHealth: {
        parameters: {
            query?: {
                probe_network?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceHealthReport"];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    createStoryFromSourceItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceItemIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listStories: {
        parameters: {
            query?: {
                status?: components["schemas"]["StoryStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"][];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    createStory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getAudioClip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getProductionManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionManifest"];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    resumeStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listStoryReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRecord"][];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    submitFirstReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FirstReviewSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    submitSecondReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecondReviewSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    listStoryTransitions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateTransition"][];
                };
            };
            /** @description Requested story was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description State or version conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Request validation or source policy error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unexpected internal failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Fetcher, LLM, or TTS provider failure. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Required service is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
