export const queryKeys = {
  stories: (status?: string) => ['stories', status ?? 'all'] as const,
  story: (storyId: string) => ['story', storyId] as const,
  reviews: (storyId: string) => ['story', storyId, 'reviews'] as const,
  transitions: (storyId: string) => ['story', storyId, 'transitions'] as const,
  manifest: (storyId: string) => ['story', storyId, 'manifest'] as const,
  visualAssets: (storyId: string) => ['story', storyId, 'visual-assets'] as const,
  sourceMedia: (storyId: string) => ['story', storyId, 'source-media'] as const,
  sourceTranscriptions: (storyId: string, artifactId: string) => (
    ['story', storyId, 'source-media', artifactId, 'transcriptions'] as const
  ),
  classificationMetrics: () => ['metrics', 'classification'] as const,
  sourceHealth: (probeNetwork: boolean) => ['sources', 'health', {probeNetwork}] as const,
  roles: (enabled?: boolean | null) => ['roles', enabled ?? 'all'] as const,
  role: (profileId: string) => ['roles', profileId] as const,
  sourceRuns: () => ['source-runs'] as const,
  sourceSchedule: () => ['source-schedule'] as const,
  sourceRun: (runId: string) => ['source-runs', runId] as const,
  sourceCollectors: () => ['sources', 'collectors'] as const,
  videoBatches: () => ['video', 'batches'] as const,
  videoBatch: (batchId: string) => ['video', 'batches', batchId] as const,
  bgmTracks: () => ['video', 'bgm'] as const,
  operationRuns: () => ['operations', 'runs'] as const,
  schedules: () => ['operations', 'schedules'] as const,
};
