import type {ScriptDocument, Story} from '../api/types';

export const storyFixture = {
  story_id: '0f6deee6-d05e-4a70-88df-30dd551bac81',
  trace_id: '3327dabe-fdde-493e-b4c7-e824e266ffb0',
  status: 'PENDING_FIRST_REVIEW',
  source: {
    kind: 'text',
    source_uri: 'text://user-upload',
    final_uri: 'text://user-upload',
    title: '陌生人把走失的小狗送回了家',
    author: null,
    published_at: null,
    detected_language: 'zh-CN',
    fetcher: 'text',
    fetched_at: '2026-07-11T08:00:00Z',
    content_sha256: 'a'.repeat(64),
  },
  original_text: '下雨天，一位陌生人陪着走失的小狗寻找主人。',
  target_language: 'zh-CN',
  preferences: {
    style: '准确、克制',
    target_duration_seconds: 60,
    speaker_id: 'narrator',
    emotion: 'warm',
    speed: 1,
    pitch: 0,
  },
  translation: {
    source_language: 'zh-CN',
    target_language: 'zh-CN',
    translated_text: '一位陌生人帮助走失的小狗回家。',
    summary: '雨天里的善意接力。',
    key_points: ['陪伴寻找', '安全回家'],
    screening: {
      model_category: 'cats_dogs',
      category: 'cats_dogs',
      model_candidate_recommendation: true,
      candidate_recommendation: true,
      confidence: 0.92,
      rationale: '故事主体是帮助走失犬只回家。',
      risk_flags: [],
      secondary_categories: ['kindness'],
    },
  },
  script: null,
  audio: null,
  last_failure: null,
  version: 3,
  created_at: '2026-07-11T08:00:00Z',
  updated_at: '2026-07-11T08:01:00Z',
} as Story;

export const scriptFixture = {
  revision: 1,
  title: '雨天里的善意',
  language: 'zh-CN',
  segments: [
    {
      segment_id: 'a4e83d19-35b8-4f8c-9098-384b1897a790',
      sequence: 0,
      text: '雨下得很大。',
      speaker_id: 'narrator',
      emotion: 'calm',
      speed: 1,
      pitch: 0,
      visual_hint: null,
    },
    {
      segment_id: '7dfbda2e-9b88-451a-b8fb-866cb5c3a498',
      sequence: 1,
      text: '但有人停下了脚步。',
      speaker_id: 'narrator',
      emotion: 'warm',
      speed: 1,
      pitch: 0,
      visual_hint: '雨伞和小狗',
    },
  ],
} as ScriptDocument;
