import {TemplateDefinitionSchema, type TemplateDefinition} from '../schema';

export const worldWarmthTemplate: TemplateDefinition =
  TemplateDefinitionSchema.parse({
    template_id: 'world_warmth',
    template_version: '1.0.0',
    display_name: 'World Warmth Editorial',
    capabilities: {
      supported_profiles: ['douyin_vertical', 'bilibili_horizontal'],
      supported_modules: [
        'host_evidence',
        'evidence_fullscreen',
        'source_video',
      ],
      supports_bilingual_captions: true,
      supports_live2d: true,
      supports_source_attribution: true,
    },
    scene_variants: [
      {
        variant_id: 'host_split_editorial',
        module_id: 'host_evidence',
        display_name: 'Host and editorial evidence split',
        supported_profiles: ['douyin_vertical', 'bilibili_horizontal'],
        supported_host_slots: ['primary', 'corner'],
        asset_requirements: [
          {
            asset_type: 'image',
            required: false,
            minimum: 0,
            maximum: 1,
          },
          {
            asset_type: 'source_screenshot',
            required: false,
            minimum: 0,
            maximum: 1,
          },
        ],
        minimum_visual_assets: 1,
        maximum_visual_assets: 1,
      },
      {
        variant_id: 'host_corner_full_bleed',
        module_id: 'host_evidence',
        display_name: 'Full bleed evidence with corner host',
        supported_profiles: ['douyin_vertical', 'bilibili_horizontal'],
        supported_host_slots: ['corner'],
        asset_requirements: [
          {
            asset_type: 'image',
            required: false,
            minimum: 0,
            maximum: 1,
          },
          {
            asset_type: 'source_screenshot',
            required: false,
            minimum: 0,
            maximum: 1,
          },
        ],
        minimum_visual_assets: 1,
        maximum_visual_assets: 1,
      },
      {
        variant_id: 'evidence_documentary',
        module_id: 'evidence_fullscreen',
        display_name: 'Documentary full-screen evidence',
        supported_profiles: ['douyin_vertical', 'bilibili_horizontal'],
        supported_host_slots: [],
        asset_requirements: [
          {
            asset_type: 'image',
            required: false,
            minimum: 0,
            maximum: 1,
          },
          {
            asset_type: 'source_screenshot',
            required: false,
            minimum: 0,
            maximum: 1,
          },
        ],
        minimum_visual_assets: 1,
        maximum_visual_assets: 1,
      },
      {
        variant_id: 'source_video_clean',
        module_id: 'source_video',
        display_name: 'Clean reviewed source video',
        supported_profiles: ['douyin_vertical', 'bilibili_horizontal'],
        supported_host_slots: [],
        asset_requirements: [],
      },
    ],
    default_scene_variants: {
      host_evidence: 'host_split_editorial',
      evidence_fullscreen: 'evidence_documentary',
      source_video: 'source_video_clean',
    },
    layout_preset: {
      preset_id: 'world_warmth_responsive',
      profiles: [
        {
          profile_id: 'douyin_vertical',
          safe_area_top: 0.045,
          safe_area_right: 0.055,
          safe_area_bottom: 0.11,
          safe_area_left: 0.055,
          host_primary_width: 0.58,
          host_corner_width: 0.38,
          caption_max_width: 0.9,
          media_fit: 'cover',
        },
        {
          profile_id: 'bilibili_horizontal',
          safe_area_top: 0.045,
          safe_area_right: 0.04,
          safe_area_bottom: 0.075,
          safe_area_left: 0.04,
          host_primary_width: 0.32,
          host_corner_width: 0.22,
          caption_max_width: 0.78,
          media_fit: 'cover',
        },
      ],
    },
    design_tokens: {
      font_family:
        'Inter, "Noto Sans CJK SC", "Microsoft YaHei", sans-serif',
      title_font_family: 'Inter, "Noto Sans CJK SC", sans-serif',
      body_font_family: 'Inter, "Noto Sans CJK SC", sans-serif',
      caption_font_family: 'Inter, "Noto Sans CJK SC", sans-serif',
      mono_font_family: '"IBM Plex Mono", Consolas, monospace',
      background: '#101512',
      foreground: '#f3f1e8',
      accent: '#85a77d',
      signal: '#e4a853',
      panel: '#182019',
      muted: '#a8b4a8',
      title_scale: 1,
      body_scale: 1,
      caption_scale: 1,
      title_weight: 760,
      body_weight: 500,
      caption_weight: 650,
      line_height: 1.32,
      corner_radius: 30,
      border_width: 2,
      shadow_blur: 48,
      panel_opacity: 0.88,
      spacing_unit: 8,
      caption_max_lines: 3,
      animation_speed: 1,
      animation_easing: 'ease-out',
      image_zoom_min: 1,
      image_zoom_max: 1.04,
    },
    intro_variant: 'world_warmth_intro',
    outro_variant: 'world_warmth_outro',
    transition_pack: 'soft_editorial',
    caption_preset: 'bilingual_editorial',
    source_bar_preset: 'verified_source',
    host_preset: 'restrained_presenter',
    static_asset_requirements: [],
  });
